### ISSUE TITLE
Add Chinese Social Media Links for Weibo and QQ in the footer or the last row of Icons

### ISSUE THREAD

**Issue by eminogrande** [aeternity/web-dev#62]
The logos/icons need to be changed into pink color.

![image](https://user-images.githubusercontent.com/3612477/73289114-69c05d80-41fc-11ea-998e-efeb84259876.png)

Weibo: https://weibo.com/aechinacn

![image](https://user-images.githubusercontent.com/3612477/73289177-878dc280-41fc-11ea-84ef-d6ba3eda502f.png)

QQ: http://qm.qq.com/cgi-bin/qm/qr?k=SyRwX1h8CaeNyGpLfy0r74EYqwJ6KERj#

**Comment by venimus** [comment]
Done
