### ISSUE TITLE
Dacade course description not accurate

### ISSUE THREAD

**Issue by moritzfelipe** [aeternity/web-dev#67]
Currently, you get learning points for your submission on ae dev 101 on dacade but no real certificate as stated in the text.

I suggest this text instead:
"Check out the highly recommended æternity 101 course on Dacade, a peer learning platform.  A video tutorial will show you how to build your own æpp, you will get feedback and might earn æ tokens for it."

**Comment by venimus** [comment]
Note: There is no more ae token reward, also rewards might get removed anyways
