### ISSUE TITLE
Choose a mining client link under miner section is the same as Join an existing mining pool

### ISSUE THREAD

**Issue by Shelpin** [aeternity/web-dev#91]
Hi!! The two boxes at the right link to the same aeknow page...Not sure though which is the most updated link for chosing a mining client. 

![image](https://user-images.githubusercontent.com/21328788/100094480-6831e700-2e59-11eb-9dce-8aebf82ea9ae.png)

**Comment by venimus** [comment]
You are right, unfortunately both things are on the same page
